name: Build & Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Branch
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      -
        name: Repository
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
