name: Build & Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.0
      - name: Print environment variables
        run: |
          echo $GITHUB_REPOSITORY_SLUG + "\n"
          echo $GITHUB_REPOSITORY_OWNER + "\n"
          echo $GITHUB_REPOSITORY_OWNER_SLUG + "\n"
          echo $GITHUB_REPOSITORY_NAME + "\n"
          echo $GITHUB_REPOSITORY_NAME_SLUG + "\n"
          echo $GITHUB_REF_SLUG + "\n"
          echo $GITHUB_REF_NAME + "\n"
          echo $GITHUB_REF_NAME_SLUG + "\n"
          echo $GITHUB_SHA_SHORT + "\n"
